import type { Metadata } from "next";
import "./globals.css";
import Navbar from "./candidate/components/candidate-Navbar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-gray-100 text-gray-900 min-h-screen flex flex-col">
        <Navbar />

        <main className="flex-grow container mx-auto p-6">{children}</main>
      </body>
    </html>
  );
}
